- id: indoor_lights_at_sunset
  alias: Indoor lights at sunset
  trigger:
  - event: sunset
    platform: sun
    offset: "-01:00:00"
  action:
  - data:
      entity_id:
        - group.living_room_lights
        - group.hall_lights
    service: light.turn_on

- id: turn_off_lights_when_off_to_work
  alias: Turn off lights when off to work
  trigger:
    - platform: state
      entity_id: person.ricardo
      from: 'home'
      to: 'not_home'
  condition:
    - condition: time
      after: '08:00'
      before: '18:00'
  action:
    - service: light.turn_off
      data:
        entity_id: group.all_lights

- id: turn_off_lights_before_sleep
  alias: Turn off lights before sleep
  trigger:
    - platform: state
      entity_id: sensor.room_presence
      to: 'bedroom'
      for: '00:05:00'
  condition:
    - condition: time
      after: '21:00'
      before: '06:00'
  action:
    - service: light.turn_off
      data:
        entity_id: group.living_room_lights
