- id: indoor_lights_at_sunset
  alias: Indoor lights at sunset
  trigger:
  - event: sunset
    platform: sun
    offset: "-01:00:00"
  action:
  - data:
      entity_id:
        - group.living_room_lights
        - group.hall_lights
    service: light.turn_on

- id: turn_off_lights_when_off_to_work
  alias: Turn off lights when off to work
  trigger:
    - platform: state
      entity_id: person.ricardo
      from: 'home'
      to: 'not_home'
  condition:
    - condition: time
      after: '08:00'
      before: '18:00'
  action:
    - service: light.turn_off
      data:
        entity_id: group.all_lights

- id: turn_off_lights_before_sleep
  alias: Turn off lights before sleep
  trigger:
    - platform: state
      entity_id: sensor.room_presence
      to: 'bedroom'
      for: '00:05:00'
  condition:
    - condition: time
      after: '21:00'
      before: '06:00'
  action:
    - service: light.turn_off
      data:
        entity_id: group.living_room_lights

#####################
# Hue Dimmer Switch #
#####################

- alias: 'Dimmer 1st button'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: dimmer_switch
      event: 1002
  action:
    service: light.toggle
    entity_id: group.living_room_lights

- alias: 'Dimmer 2nd button'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: dimmer_switch
      event: 2002
  action:
    service: light.toggle
    entity_id: group.hall_lights

- alias: 'Dimmer 3rd button'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: dimmer_switch
      event: 3002
  action:
    service: light.toggle
    entity_id: light.smartplug_quarto

- alias: 'Dimmer 4th button'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: dimmer_switch
      event: 4002
  action:
    service: light.toggle
    entity_id: group.bedroom_lights
