- id: indoor_lights_at_sunset
  alias: Indoor lights at sunset
  trigger:
  - platform: state
    entity_id: sensor.daylight
    to: 'golden_hour_2'
  action:
  - data:
      entity_id:
        - group.living_room_lights
        - group.hall_lights
    service: light.turn_on

- id: turn_off_lights_when_off_to_work
  alias: Turn off lights when off to work
  trigger:
    - platform: state
      entity_id: sensor.ricardo_presence
      to: 'not_home'
  condition:
    - condition: time
      after: '08:00'
      before: '18:00'
  action:
    - service: light.turn_off
      data:
        entity_id: group.all_lights

- id: turn_off_lights_before_sleep
  alias: Turn off lights before sleep
  trigger:
    - platform: state
      entity_id: sensor.room_presence
      to: 'bedroom'
      for: '00:05:00'
  condition:
    - condition: time
      after: '21:00'
      before: '06:00'
  action:
    - service: light.turn_off
      data:
        entity_id: group.living_room_lights

- alias: 'Hue Dimmer Switch'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: dimmer_switch
  condition:
    - condition: template
      value_template: "{{ trigger.event.data.event|int in [1002, 2002, 3002, 4002] }}"
  action:
    service_template: >
      {% set service_mapping = {1002: 'light.toggle',  2002: 'light.toggle',
                                3002: 'switch.toggle', 4002: 'switch.toggle'} %}
      {{ service_mapping[trigger.event.data.event|int] }}
    data_template:
      entity_id: >
        {% set event_mapping = {1002: 'group.living_room_lights',
                                2002: 'group.hall_lights',
                                3002: 'switch.smartplug_quarto',
                                4002: 'switch.bedroom_lamp'} %}
        {{ event_mapping[trigger.event.data.event|int] }}
