---
- alias: Hue Dimmer Switch
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
  condition:
  - condition: template
    value_template: "{{ trigger.event.data.id in ['dimmer_switch_living_room'] }}"
  - condition: template
    value_template: "{{ trigger.event.data.event|int in [1002, 2002, 3002, 4002] }}"
  action:
    service_template: |
      {% set service_mapping = {1002: 'light.toggle',  2002: 'light.toggle',
                                3002: 'switch.toggle', 4002: 'light.toggle'} %}
      {{ service_mapping[trigger.event.data.event|int] }}
    data_template:
      entity_id: |
        {% set event_mapping = {1002: 'group.living_room_lights',
                                2002: 'group.hall_lights',
                                4002: 'light.kitchen_light'} %}
        {{ event_mapping[trigger.event.data.event|int] }}
  id: c515b0c653ed444a929abb64c0a10b75
- alias: Kitchen Light Switch
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: kitchen_switch
      event: 1002
  action:
    service: light.toggle
    data:
      entity_id: light.kitchen_light
  id: d010cbde411a42c7a8fca11e9be51020
- alias: Living Room Light Switch
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: living_room_switch
  action:
    service_template: |
      {% set service_mapping = {1002: 'light.toggle',
                                2002: 'script.turn_on',
                                2004: 'switch.toggle',
                                3002: 'switch.toggle'} %}
      {{ service_mapping[trigger.event.data.event|int] }}
    data_template:
      entity_id: |
        {% set event_mapping = {1002: 'group.living_room_lights',
                                2002: 'script.living_room_corner',
                                2004: 'switch.desk_lamp',
                                3002: 'switch.relax_scene'} %}
        {{ event_mapping[trigger.event.data.event|int] }}
  id: ba62983b42e24ac8ab1ba70a4f33bea1
- alias: Hue Dimmer Switch
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
  condition:
  - condition: template
    value_template: "{{ trigger.event.data.id in ['dimmer_switch'] }}"
  - condition: template
    value_template: "{{ trigger.event.data.event|int in [1002, 2002, 3002, 4002] }}"
  action:
    service_template: |
      {% set service_mapping = {1002: 'light.toggle',  2002: 'light.toggle',
                                3002: 'switch.toggle', 4002: 'switch.toggle'} %}
      {{ service_mapping[trigger.event.data.event|int] }}
    data_template:
      entity_id: |
        {% set event_mapping = {1002: 'light.bedroom_light',
                                3002: 'switch.smartplug_quarto',
                                4002: 'switch.bedroom_lamp'} %}
        {{ event_mapping[trigger.event.data.event|int] }}
  id: 835ab46162ce45b1a0c613af59609bb5
- id: turn_off_lights_when_off_to_work
  alias: Turn off lights when off to work
  trigger:
  - platform: state
    entity_id: sensor.ricardo_presence
    to: not_home
    for: '00:05:00'
  condition:
  - condition: time
    after: '08:00'
    before: '18:00'
  action:
  - service: light.turn_off
    data:
      entity_id: all
  - service: switch.turn_off
    data:
      entity_id:
      - group.all_living_room_devices
      - switch.smartplug_quarto
      - switch.bedroom_lamp
- alias: Bedroom Light Switch
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bedroom_switch
  action:
    service_template: |
      {% set service_mapping = {1001: 'switch.toggle',
                                1002: 'light.toggle',
                                1004: 'switch.toggle'} %}
      {{ service_mapping[trigger.event.data.event|int] }}
    data_template:
      entity_id: |
        {% set event_mapping = {1001: 'switch.smartplug_quarto',
                                1002: 'light.bedroom_light',
                                1004: 'switch.bedroom_lamp'} %}
        {{ event_mapping[trigger.event.data.event|int] }}
  id: f6d705ea4db14d47bb54cbd26330cf1a
- id: '1581175320226'
  alias: Pull updated configuration
  trigger:
  - platform: webhook
    webhook_id: update_configuration
  action:
  - service: shell_command.git_pull
  - service: homeassistant.check_config
  - service: homeassistant.restart
