homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Lisbon
  # Customization file
  customize: !include customize.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Show the introduction message on startup.
# introduction:

recorder:
  db_url: !secret postgres_url

influxdb:
  host: !secret influxdb_host
  username: !secret influxdb_username
  password: !secret influxdb_password
  database: !secret influxdb_database

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: !secret http_base_url
  use_x_forwarded_for: true
  # Trust the Docker container host
  trusted_proxies: !secret http_trusted_proxies

# Discover some devices automatically
discovery:

lovelace:
  mode: yaml

binary_sensor:
  - platform: meteoalarm
    country: 'PT'
    province: 'SETÚBAL'

  - platform: template
    sensors:
      bed_presence:
        friendly_name: "Bed presence"
        value_template: '{{ states("sensor.bed_pressure") | float >= 1.00 }}'
        delay_off:
          minutes: 2

  - platform: workday
    country: PTE

  - platform: trend
    sensors:
      humidity_increasing:
        friendly_name: "Humidity Increasing"
        entity_id: sensor.bedroom_humidity
        min_gradient: 0.001

mqtt:
  broker: !secret mqtt_broker
  client_id: "home-assistant"

device_tracker: !include device_tracker.yaml

# Devices
neato:
  username: !secret neato_username
  password: !secret neato_password

input_boolean:
  relaxing:
    name: "Relax scene is on"
    initial: false
  extended_away:
    name: "Extended Away"
    initial: false
    icon: mdi:beach

switch:
  - platform: template
    switches:
      relax_scene:
        friendly_name: "Relax scene"
        icon_template: 'mdi:headphones'
        value_template: "{{ is_state('input_boolean.relaxing', 'on') }}"
        turn_on:
          - service: input_boolean.turn_on
            data:
              entity_id: input_boolean.relaxing
          - service: scene.turn_on
            data:
              entity_id: scene.relax
        turn_off:
          - service: input_boolean.turn_off
            data:
              entity_id: input_boolean.relaxing
          - service: scene.turn_on
            data:
              entity_id: scene.regular_lights

notify:
  - name: slack
    platform: slack
    api_key: !secret slack_api_key
    default_channel: !secret slack_default_channel

group: !include groups.yaml
sensor: !include_dir_list sensors
automation: !include_dir_list automations
script: !include scripts.yaml
frontend: !include frontend.yaml
scene: !include scene.yaml

hacs:
  token: !secret github_token
