homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Lisbon
  # Customization file
  customize: !include customize.yaml
  internal_url: !secret http_base_url
  external_url: !secret http_base_url

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Show the introduction message on startup.
# introduction:

logger:
  default: warning
  logs:
    homeassistant.components.esphome: warning
    WazeRouteCalculator.WazeRouteCalculator: warning

recorder:
  db_url: !secret postgres_url

influxdb:
  host: !secret influxdb_host
  username: !secret influxdb_username
  password: !secret influxdb_password
  database: !secret influxdb_database
  tags_attributes:
    - 'friendly_name'

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  use_x_forwarded_for: true
  # Trust the Docker container host
  trusted_proxies: !secret http_trusted_proxies

# Discover some devices automatically
discovery:

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/group-card/group-card.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/banner-card/banner-card.js
      type: module
    - url: /hacsfiles/simple-weather-card/simple-weather-card-bundle.js
      type: module
    - url: /hacsfiles/lovelace-card-templater/lovelace-card-templater.js
      type: js
    - url: /hacsfiles/weather-card/weather-card.js
      type: module
    - url: /hacsfiles/custom-header/custom-header.js
      type: module
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /hacsfiles/vacuum-card/vacuum-card.js
      type: module

binary_sensor:
  - platform: workday
    country: PTE

mqtt:
  broker: !secret mqtt_broker
  client_id: "home-assistant"
  discovery: true

# Devices
neato:
  username: !secret neato_username
  password: !secret neato_password

input_boolean:
  relaxing:
    name: "Relax scene is on"
    initial: false
  extended_away:
    name: "Extended Away"
    initial: false
    icon: mdi:beach

switch:
  - platform: template
    switches:
      relax_scene:
        friendly_name: "Relax scene"
        icon_template: 'mdi:headphones'
        value_template: "{{ is_state('input_boolean.relaxing', 'on') }}"
        turn_on:
          - service: input_boolean.turn_on
            data:
              entity_id: input_boolean.relaxing
          - service: scene.turn_on
            data:
              entity_id: scene.relax
        turn_off:
          - service: input_boolean.turn_off
            data:
              entity_id: input_boolean.relaxing
          - service: scene.turn_on
            data:
              entity_id: scene.regular_lights

  - platform: mqtt
    icon: 'mdi:car-defrost-rear'
    name: 'Towel Heater'
    state_topic: 'towelheater/switch/towel_heater/state'
    command_topic: 'towelheater/switch/towel_heater/command'
    # availability_topic: 'towelheater/status'
    qos: 1
    retain: true
    optimistic: true

group: !include groups.yaml
sensor: !include_dir_list sensors
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scene.yaml

frontend:
  themes: !include_dir_merge_named themes

hacs:
  token: !secret github_token

shell_command:
  git_pull: git pull --autostash --rebase origin master
  turn_on_towelheater: mosquitto_pub -t 'towelheater/switch/towel_heater/command' -m 'ON' -D PUBLISH message-expiry-interval 300 -r -h nanopct4.lab.badmood.club
