title: Home
views:
  - cards:
      - type: entities
        title: Information
        show_header_toggle: false
        entities:
          - sensor.work_commute
          - sensor.home_commute
      - type: vertical-stack
        cards:
          - entities:
              - entity: group.living_room_lights
              - entity: group.hall_lights
            title: Light
            type: entities
          - type: entities
            title: Power plugs
            entities:
              - entity: light.smartplug_quarto
              - entity: light.smartplug_sala
      - type: picture-entity
        entity: vacuum.neato
        camera_image: camera.neato_cleaning_map
    path: default_view
    title: Home
    icon: 'mdi:home-assistant'

  - icon: mdi:weather-cloudy
    id: weather
    title: Weather
    cards:
      - type: vertical-stack
        cards:
        - entity: weather.home
          type: weather-forecast
        - type: iframe
          aspectratio: 100%
          url: !secret windy_embed_url
