title: Home
custom_header:
  compact_mode: true
views:
  - cards:
      - type: vertical-stack
        cards:
        - type: custom:banner-card
          heading: "\U0001F6CB Living room"
          link: /lovelace/living_room
          row_size: 5
          entities:
            - entity: light.living_room
              name: Light
            - entity: switch.desk_lamp
              name: Desk Lamp
            - entity: switch.smartplug_sala
              name: Heater / Fan
            - entity: sensor.living_room_temperature
              name: Temperature
            - entity: sensor.living_room_humidity
              name: Humidity
        - type: custom:banner-card
          heading: "\U0001F6CF Bedroom"
          link: /lovelace/bedroom
          row_size: 5
          entities:
            - entity: light.bedroom_light
              name: Light
            - entity: switch.bedroom_lamp
              name: Lamp
            - entity: switch.smartplug_quarto
              name: Heater / Fan
            - entity: sensor.bedroom_temperature
              name: Temperature
            - entity: sensor.bedroom_humidity
              name: Humidity
        - type: custom:banner-card
          heading: "\U0001F6C1 Bathroom"
          link: /lovelace/bathroom
          row_size: 4
          entities:
            - entity: light.bathroom
              name: Lights
            - entity: switch.towel_heater
              name: Towel Heater
            - entity: sensor.bathroom_temperature
              name: Temperature
            - entity: sensor.bathroom_relative_humidity
              name: Humidity
      - type: entities
        entities:
          - sensor.hacs
      - type: entities
        title: Information
        show_header_toggle: false
        entities:
          - sensor.work_commute
          - sensor.home_commute
      - type: 'custom:vacuum-card'
        entity: vacuum.neato
        image: '/local/images/neato-botvac-d5.svg'
        actions:
          - name: Eco
            service: neato.custom_cleaning
            icon: 'mdi:leaf'
            service_data:
              entity_id: vacuum.neato
              mode: 1
              navigation: 2
              category: 4
          - name: Turbo
            service: neato.custom_cleaning
            icon: 'mdi:clock-fast'
            service_data:
              entity_id: vacuum.neato
              mode: 2
              navigation: 2
              category: 4
    path: default_view
    title: Home
    icon: 'mdi:home-assistant'

  - icon: mdi:weather-cloudy
    id: weather
    title: Weather
    cards:
      - type: vertical-stack
        cards:
        - type: custom:weather-card
          entity: weather.home
        - type: iframe
          aspectratio: 100%
          url: !secret windy_embed_url
      - type: vertical-stack
        cards:
          - type: custom:mini-graph-card
            hour24: true
            points_per_hour: 12
            hours_to_show: 3
            lower_bound: ~15
            upper_bound: ~30
            name: Room Temperature
            align_icon: left
            align_header: left
            entities:
              - entity: sensor.bedroom_temperature
                name: Bedroom
              - entity: sensor.living_room_temperature
                name: Living Room
          - type: custom:mini-graph-card
            hour24: true
            points_per_hour: 12
            hours_to_show: 3
            name: Room Humidity
            align_icon: left
            align_header: left
            entities:
              - entity: sensor.bedroom_humidity
                name: Bedroom
              - entity: sensor.living_room_humidity
                name: Living Room
          - type: custom:mini-graph-card
            hour24: true
            points_per_hour: 12
            hours_to_show: 3
            name: Room Air Pressure
            align_icon: left
            align_header: left
            entities:
              - entity: sensor.bedroom_pressure
                name: Bedroom
              - entity: sensor.living_room_pressure
                name: Living Room

  - icon: mdi:puzzle
    id: misc
    title: Misc
    cards:
      - type: entities
        title: Hall
        show_header_toggle: false
        entities:
          - light.hue_white_lamp_corredor
          - type: divider
          - sensor.raw_hall_brightness
          - binary_sensor.presence_21
      - type: entities
        title: Kitchen
        show_header_toggle: false
        entities:
          - light.kitchen_light
          - type: divider
          - sensor.aqara_kitchen_temperature
          - sensor.aqara_kitchen_humidity
          - sensor.lightlevel_19
          - binary_sensor.presence_18
      - type: custom:auto-entities
        card:
          type: entities
        filter:
          include:
            - entity_id: 'sensor.*_battery*'
        sort:
          method: 'state'
          numeric: true

  - icon: mdi:sofa
    path: living_room
    id: living-room
    title: Living Room
    cards:
      - type: vertical-stack
        cards:
        - type: entities
          show_header_toggle: false
          entities:
            - light.hue_white_lamp_sala_pc
            - light.hue_white_lamp_sala_janela
            - type: divider
            - switch.living_room_corner_light
            - switch.living_room_big_corner_light
            - switch.desk_lamp
            - type: divider
            - switch.smartplug_sala
            - entity: switch.innr_on_off_light_1
              secondary_info:
                entity: sensor.innr_on_off_light_1_power
                prefix: "Current power usage: "
                postfix: " W"
            - type: divider
            - type: buttons
              entities:
                - entity: light.antares_screen
                  icon: mdi:brightness-2
                  tap_action:
                    action: call-service
                    service: light.turn_on
                    service_data:
                      entity_id: light.antares_screen
                      brightness: 1
                - entity: light.antares_screen
                  icon: mdi:brightness-4
                  tap_action:
                    action: call-service
                    service: light.turn_on
                    service_data:
                      entity_id: light.antares_screen
                      brightness: 20
                - entity: light.antares_screen
                  icon: mdi:brightness-5
                  tap_action:
                    action: call-service
                    service: light.turn_on
                    service_data:
                      entity_id: light.antares_screen
                      brightness_pct: 50
      - type: horizontal-stack
        cards:
        - type: entity-button
          entity: scene.late_night_relax
          tap_action:
            action: call-service
            service: scene.turn_on
            service_data:
              entity_id: scene.late_night_relax
        - type: entity-button
          entity: scene.relax
          tap_action:
            action: call-service
            service: scene.turn_on
            service_data:
              entity_id: scene.relax
        - type: entity-button
          entity: scene.regular_lights
          tap_action:
            action: call-service
            service: scene.turn_on
            service_data:
              entity_id: scene.regular_lights
      - type: vertical-stack
        cards:
        - type: gauge
          entity: sensor.living_room_discomfort_index
          min: 21
          max: 32
          severity:
            - green: 21
            - yellow: 24
            - red: 27
        - type: custom:mini-graph-card
          line_color: '#f1c40f'
          show:
            extrema: true
            fill: false
            labels: true
          animate: true
          hours_to_show: 6
          points_per_hour: 4
          hour24: true
          lower_bound: ~15
          upper_bound: ~30
          name: Temperature
          entities:
            - sensor.living_room_temperature
        - type: horizontal-stack
          cards:
          - type: custom:mini-graph-card
            font_size: 75
            line_width: 8
            line_color: '#3498db'
            show:
              fill: false
              labels: false
            animate: true
            hours_to_show: 6
            points_per_hour: 4
            hour24: true
            name: Humidity
            entities:
              - sensor.living_room_humidity
          - type: custom:mini-graph-card
            font_size: 75
            line_width: 8
            line_color: '#9b59b6'
            show:
              fill: false
              labels: false
            animate: true
            hours_to_show: 6
            points_per_hour: 4
            hour24: true
            name: Pressure
            entities:
              - sensor.living_room_pressure

  - icon: mdi:bed-empty
    path: bedroom
    id: bedroom
    title: Bedroom
    cards:
      - type: entities
        show_header_toggle: false
        entities:
          - light.bedroom_light
          - switch.bedroom_lamp
          - type: divider
          - switch.smartplug_quarto
      - type: vertical-stack
        cards:
        - type: custom:mini-graph-card
          line_color: '#f1c40f'
          show:
            extrema: true
            fill: false
          animate: true
          hours_to_show: 6
          points_per_hour: 4
          hour24: true
          lower_bound: ~15
          upper_bound: ~30
          name: Temperature
          entities:
            - sensor.bedroom_temperature
        - type: horizontal-stack
          cards:
          - type: custom:mini-graph-card
            font_size: 75
            line_width: 8
            line_color: '#3498db'
            show:
              fill: false
              labels: false
            animate: true
            hours_to_show: 6
            points_per_hour: 4
            hour24: true
            name: Humidity
            entities:
              - sensor.bedroom_humidity
          - type: custom:mini-graph-card
            font_size: 75
            line_width: 8
            line_color: '#9b59b6'
            show:
              fill: false
              labels: false
            animate: true
            hours_to_show: 6
            points_per_hour: 4
            hour24: true
            name: Pressure
            entities:
              - sensor.bedroom_pressure
        - type: glance
          entities:
            - binary_sensor.bed_presence
            - sensor.bed_pressure
            - binary_sensor.presence_20

  - icon: mdi:shower
    path: bathroom
    id: bathroom
    title: Bathroom
    cards:
      - type: entities
        show_header_toggle: false
        entities:
          - light.bathroom_overhead_light
          - light.bathroom_mirror_light
      - type: glance
        entities:
          - entity: sensor.bathroom_temperature
            name: Temperature
          - entity: sensor.bathroom_relative_humidity
            name: Humidity
          - entity: binary_sensor.bathroom_presence
            name: Presence
      - type: vertical-stack
        in_card: true
        cards:
          - type: custom:mini-graph-card
            line_color: '#3498db'
            show:
              extrema: true
              fill: false
              labels: true
            animate: true
            hours_to_show: 1
            points_per_hour: 30
            hour24: true
            name: Humidity
            entities:
              - sensor.bathroom_relative_humidity
          - type: custom:mini-graph-card
            line_color: '#3498db'
            show:
              extrema: true
              fill: false
              labels: true
              state: false
            animate: true
            hours_to_show: 1
            points_per_hour: 30
            hour24: true
            name: Absolute Humidity
            entities:
              - sensor.bme280_bathroom_absolute_humidity
      - type: entity-button
        entity: switch.towel_heater
