title: Home
resources:
  - url: /community_plugin/group-card/group-card.js
    type: module
  - url: /community_plugin/mini-graph-card/mini-graph-card.js
    type: module
  - url: /community_plugin/banner-card/banner-card.js
    type: module
  - url: /community_plugin/simple-weather-card/simple-weather-card.js
    type: module
  - url: /community_plugin/lovelace-card-templater/card-templater.js
    type: js
  - url: /community_plugin/weather-card/weather-card.js
    type: module
  - url: /community_plugin/compact-custom-header/compact-custom-header.js
    type: module
cch:
  swipe: 'true'
  exceptions:
    - conditions:
        media_query: '(max-width: 600px)'
      config:
        notifications: 'overflow'
        voice: 'hide'
views:
  - cards:
      - type: vertical-stack
        cards:
        - type: custom:banner-card
          background: "#EDE7B0"
          heading: "\U0001F6CB Living room"
          link: /lovelace/living_room
          entities:
            - entity: light.living_room
              name: Light
            - entity: sensor.living_room_temperature
              name: Temperature
            - entity: sensor.living_room_humidity
              name: Humidity
        - type: custom:banner-card
          background: "#91CCEC"
          heading: "\U0001F6CF Bedroom"
          link: /lovelace/bedroom
          entities:
            - entity: switch.bedroom_lamp
              name: Lamp
            - entity: sensor.bedroom_temperature
              name: Temperature
            - entity: sensor.bedroom_humidity
              name: Humidity
        - type: custom:banner-card
          heading: "\U0001F6C1 Bathroom"
          entities:
            - entity: switch.towel_heater
              name: Towel Heater
            - entity: sensor.bathroom_temperature
              name: Temperature
            - entity: sensor.bathroom_relative_humidity
              name: Humidity
      - type: entities
        entities:
          - sensor.hacs
      - type: entities
        title: Information
        show_header_toggle: false
        entities:
          - sensor.work_commute
          - sensor.home_commute
      - type: picture-entity
        entity: vacuum.neato
        camera_image: camera.neato_cleaning_map
    path: default_view
    title: Home
    icon: 'mdi:home-assistant'

  - icon: mdi:weather-cloudy
    id: weather
    title: Weather
    cards:
      - type: vertical-stack
        cards:
        - type: custom:weather-card
          entity: weather.home
        - type: iframe
          aspectratio: 100%
          url: !secret windy_embed_url
      - type: vertical-stack
        cards:
          - type: custom:mini-graph-card
            hour24: true
            points_per_hour: 12
            hours_to_show: 3
            name: Room Temperature
            align_icon: left
            align_header: left
            entities:
              - entity: sensor.bedroom_temperature
                name: Bedroom
              - entity: sensor.living_room_temperature
                name: Living Room
          - type: custom:mini-graph-card
            hour24: true
            points_per_hour: 12
            hours_to_show: 3
            name: Room Humidity
            align_icon: left
            align_header: left
            entities:
              - entity: sensor.bedroom_humidity
                name: Bedroom
              - entity: sensor.living_room_humidity
                name: Living Room
          - type: custom:mini-graph-card
            hour24: true
            points_per_hour: 12
            hours_to_show: 3
            name: Room Air Pressure
            align_icon: left
            align_header: left
            entities:
              - entity: sensor.bedroom_pressure
                name: Bedroom
              - entity: sensor.living_room_pressure
                name: Living Room

  - icon: mdi:door
    id: hall
    title: Hall
    cards:
      - type: entities
        show_header_toggle: false
        entities:
          - light.hue_white_lamp_corredor

  - icon: mdi:sofa
    path: living_room
    id: living-room
    title: Living Room
    cards:
      - type: vertical-stack
        cards:
        - type: custom:group-card
          card:
            type: entities
            show_header_toggle: false
          group: group.living_room_lights
        - type: entities
          show_header_toggle: false
          entities:
            - switch.living_room_corner_light
        - type: entities
          show_header_toggle: false
          entities:
            - switch.smartplug_sala
      - type: horizontal-stack
        cards:
        - type: entity-button
          entity: scene.relax
          tap_action:
            action: call-service
            service: scene.turn_on
            service_data:
              entity_id: scene.relax
        - type: entity-button
          entity: scene.regular_lights
          tap_action:
            action: call-service
            service: scene.turn_on
            service_data:
              entity_id: scene.regular_lights
      - type: vertical-stack
        cards:
        - type: custom:mini-graph-card
          show:
            extrema: true
            fill: false
            labels: true
          animate: true
          hours_to_show: 6
          points_per_hour: 4
          hour24: true
          name: Temperature
          entities:
            - sensor.living_room_temperature
        - type: horizontal-stack
          cards:
          - type: custom:mini-graph-card
            font_size: 75
            line_width: 8
            show:
              fill: false
              labels: false
            animate: true
            hours_to_show: 6
            points_per_hour: 4
            hour24: true
            name: Humidity
            entities:
              - sensor.living_room_humidity
          - type: custom:mini-graph-card
            font_size: 75
            line_width: 8
            show:
              fill: false
              labels: false
            animate: true
            hours_to_show: 6
            points_per_hour: 4
            hour24: true
            name: Pressure
            entities:
              - sensor.living_room_pressure

  - icon: mdi:bed-empty
    path: bedroom
    id: bedroom
    title: Bedroom
    cards:
      - type: entities
        show_header_toggle: false
        entities:
          - switch.bedroom_lamp
      - type: entities
        show_header_toggle: false
        entities:
          - switch.smartplug_quarto
      - type: vertical-stack
        cards:
        - type: custom:mini-graph-card
          show:
            extrema: true
            fill: false
          animate: true
          hours_to_show: 6
          points_per_hour: 4
          hour24: true
          name: Temperature
          entities:
            - sensor.bedroom_temperature
        - type: horizontal-stack
          cards:
          - type: custom:mini-graph-card
            font_size: 75
            line_width: 8
            show:
              fill: false
              labels: false
            animate: true
            hours_to_show: 6
            points_per_hour: 4
            hour24: true
            name: Humidity
            entities:
              - sensor.bedroom_humidity
          - type: custom:mini-graph-card
            font_size: 75
            line_width: 8
            show:
              fill: false
              labels: false
            animate: true
            hours_to_show: 6
            points_per_hour: 4
            hour24: true
            name: Pressure
            entities:
              - sensor.bedroom_pressure
        - type: glance
          entities:
            - binary_sensor.bed_presence
            - sensor.bed_pressure

  - icon: mdi:shower
    id: bathroom
    title: Bathroom
    cards:
      - type: entity-button
        entity: switch.towel_heater
