---
alias: 'Bedroom Light Switch'
initial_state: 'on'
trigger:
  platform: event
  event_type: deconz_event
  event_data:
    id: 'bedroom_switch'
    event: 1002
action:
  service: light.toggle
  data:
    entity_id: light.bedroom_light
