---
alias: 'Bedroom Light Switch'
initial_state: 'on'
trigger:
  platform: state
  entity_id: binary_sensor.bedroom_light_push_button
  to: 'on'
action:
  service: light.toggle
  data:
    entity_id: light.bedroom_light
