---
id: indoor_lights_at_sunset
alias: Indoor lights at sunset
trigger:
  - platform: state
    entity_id: sensor.daylight
    to: 'golden_hour_2'
condition:
  - condition: state
    entity_id: input_boolean.extended_away
    state: 'off'
action:
  - service: light.turn_on
    data:
      entity_id:
        - group.living_room_lights
        - group.hall_lights
