---
alias: 'Bedroom Light Switch'
initial_state: 'on'
trigger:
  platform: event
  event_type: deconz_event
  event_data:
    id: 'living_room_switch'
action:
  service_template: >
    {% set service_mapping = {1002: 'light.toggle',
                              2002: 'switch.toggle',
                              2004: 'switch.toggle',
                              3002: 'switch.toggle'} %}
    {{ service_mapping[trigger.event.data.event|int] }}
  data_template:
    entity_id: >
      {% set event_mapping = {1002: 'group.living_room_lights',
                              2002: 'switch.living_room_big_corner_light',
                              2004: 'switch.desk_lamp',
                              3002: 'switch.relax_scene'} %}
      {{ event_mapping[trigger.event.data.event|int] }}
