---
alias: 'Prepare bedroom for sleepytimes'
trigger:
  - platform: time
    at: '23:00:00'
condition:
  - condition: state
    entity_id: input_boolean.extended_away
    state: 'off'
action:
  - service: switch.turn_on
    data:
      entity_id:
        - switch.smartplug_quarto
        - switch.bedroom_lamp
