---
alias: Turn off hall light when there's enough natural light
trigger:
  - platform: numeric_state
    entity_id: sensor.hall_brightness
    below: 6000
    for: '00:00:30'
action:
  - service: light.turn_off
    data:
      entity_id: group.hall_lights
