---
alias: Turn off towel heater after shower ends
trigger:
  - platform: state
    entity_id: binary_sensor.shower_ended
    to: 'on'
condition:
  - condition: state
    entity_id: switch.towel_heater
    state: 'on'
action:
  - service: switch.turn_off
    data:
      entity_id: switch.towel_heater
  - delay: '00:05:00'
  - service: switch.turn_on
    data:
      entity_id: switch.towel_heater_deep_sleep
