---
id: turn_off_lights_before_sleep
alias: Turn off lights before sleep
trigger:
  - platform: state
    entity_id: sensor.ricardo_presence
    to: 'bedroom'
    for: '00:05:00'
condition:
  - condition: time
    after: '21:00'
    before: '06:00'
action:
  - service: light.turn_off
    data:
      entity_id:
        - group.all_living_room_devices
        - light.kitchen_light
  - service: switch.turn_off
    data:
      entity_id:
        - group.all_living_room_devices
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.relaxing
