esphome:
  name: esp07
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain
  fast_connect: true

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

uart:
  id: uart_bus
  tx_pin: D5
  baud_rate: 9600

interval:
  - interval: 1s
    then:
      - uart.write:
          id: uart_bus
          data: "{\"bananas\": true}\r\n"
