esphome:
  name: esp05
  platform: ESP32
  board: lolin_d32_pro

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain
  fast_connect: true
  power_save_mode: light

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

sensor:
  - platform: adc
    pin: 34
    id: photoresistor
    update_interval: 10s

  - platform: resistance
    sensor: photoresistor
    configuration: UPSTREAM
    resistor: 2kOhm
    name: "Hall Brightness"
