esphome:
  name: esp07
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain
  fast_connect: true

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

deep_sleep:
  id: esp07_deep_sleep_1h
  sleep_duration: '1h'

switch:
  - platform: template
    name: "ESP-07 sleep (1h)"
    turn_on_action:
      - deep_sleep.enter: esp07_deep_sleep_1h

binary_sensor:
  - platform: gpio
    pin: D5
    name: "Push button"
