esphome:
  name: esp06
  platform: ESP32
  board: lolin_d32_pro

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: light
  fast_connect: true
  manual_ip:
    static_ip: !secret esp_06_ip
    gateway: !secret gateway
    subnet: 255.255.255.0
    dns1: !secret dns_server
    dns2: 0.0.0.0

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

mqtt:
  broker: !secret mqtt_broker
  topic_prefix: esp06

i2c:
  sda: 21
  scl: 22
  scan: True

sensor:
  - platform: adc
    pin: 34
    name: "Bed Pressure"
    update_interval: 2s
    attenuation: 11db
    filters:
      - sliding_window_moving_average:
          window_size: 3
          send_every: 3
      - lambda: 'return std::max(x, 0.0f);'

  - platform: bme280
    temperature:
      name: "BME280 Bedroom Temperature"
      id: bme280_bedroom_temperature
    pressure:
      name: "BME280 Bedroom Pressure"
      id: bme280_bedroom_pressure
    humidity:
      name: "BME280 Bedroom Relative Humidity"
      id: bme280_bedroom_humidity
    address: 0x76
    update_interval: 15s

  - platform: template
    name: "BME280 Bedroom Absolute Humidity"
    lambda: |-
      const float mw = 18.01534;    // molar mass of water g/mol
      const float r = 8.31447215;   // Universal gas constant J/mol/K
      return (6.112 * powf(2.718281828, (17.67 * id(bme280_bedroom_temperature).state) /
        (id(bme280_bedroom_temperature).state + 243.5)) * id(bme280_bedroom_humidity).state * mw) /
        ((273.15 + id(bme280_bedroom_temperature).state) * r); // in grams/m^3
    accuracy_decimals: 2
