esphome:
  name: esp02
  platform: ESP8266
  board: d1_mini
  on_loop:
    then:
      - lambda: |
          // According to https://thingpulse.com/max-deep-sleep-for-esp8266/
          // the maximum sleep duration is a bit over 3 hours, with some variance due to the RTC clock period,
          // which changes according to the temperature. For safety, assume 3 hours.
          const auto maximum_sleep_duration = 3 * 3600;

          // Make absolutely certain we're not checking before we have one minute of uptime, otherwise we risk
          // completly bogus time readings and getting into a boot loop!
          if (id(esp_02_uptime).state < 60.0f) {
              return;
          }

          // The loop runs about every 16 ms (~60 Hz).
          // That's overkill, so check only once per minute.
          static auto loop_count = 0;

          if (loop_count++ < 60 * 60) {
              return;
          }

          loop_count = 0;

          auto time = id(homeassistant_time).now();
          auto distance_to_waking_time = (19 - time.hour - 1) * 3600 + (60 - time.minute) * 60;

          ESP_LOGD("main_loop", "Distance to waking time: %d", distance_to_waking_time);

          auto sleepable_time = distance_to_waking_time < maximum_sleep_duration ? distance_to_waking_time : maximum_sleep_duration;
          if (sleepable_time <= 0) {
              return;
          }

          ESP_LOGD("main_loop", "Outside waking time, sleeping for %d s", sleepable_time);

          ESP.deepSleep(uint64_t(sleepable_time) * 1000000);

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: high
  fast_connect: true
  manual_ip:
    static_ip: !secret esp_02_ip
    gateway: !secret gateway
    subnet: 255.255.255.0
    dns1: !secret dns_server
    dns2: 0.0.0.0

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

time:
  - platform: homeassistant
    id: homeassistant_time

sensor:
  - platform: uptime
    name: "ESP-02 Uptime"
    id: esp_02_uptime

  - platform: wifi_signal
    name: "ESP-02 RSSI"
    update_interval: 60s

globals:
  - id: towel_heater_status
    type: bool
    initial_value: 'false'

switch:
  - platform: gpio
    pin: D8
    id: towel_heater_internal_switch

  - platform: template
    name: "Towel Heater"
    icon: mdi:car-defrost-rear
    lambda: 'return id(towel_heater_status);'
    turn_on_action:
      - lambda: 'id(towel_heater_status) = true;'
      - switch.turn_on: towel_heater_internal_switch
      - delay: 10ms
      - switch.turn_off: towel_heater_internal_switch
    turn_off_action:
      - lambda: 'id(towel_heater_status) = false;'
      - switch.turn_on: towel_heater_internal_switch
      - delay: 10ms
      - switch.turn_off: towel_heater_internal_switch

output:
  - platform: esp8266_pwm
    id: onboard_led
    pin:
      number: D4
      inverted: true

light:
  - platform: monochromatic
    name: "Onboard LED ESP-02"
    output: onboard_led
    id: led_1
