esphome:
  name: towelheater
  platform: ESP8266
  board: d1_mini
  on_loop:
    then:
      - lambda: |
          // According to https://thingpulse.com/max-deep-sleep-for-esp8266/
          // the maximum sleep duration is a bit over 3 hours, with some variance due to the RTC clock period,
          // which changes according to the temperature. For safety, assume 3 hours.
          const auto maximum_sleep_duration = 3 * 3600;

          // Make absolutely certain we're not checking before we have one minute of uptime, otherwise we risk
          // completly bogus time readings and getting into a boot loop!
          if (id(towel_heater_uptime).state < 60.0f) {
              return;
          }

          // The loop runs about every 16 ms (~60 Hz).
          // That's overkill, so check only once per minute.
          static auto loop_count = 0;

          if (loop_count++ < 60 * 60) {
              return;
          }

          loop_count = 0;

          auto time = id(homeassistant_time).now();
          auto distance_to_waking_time = 0;

          if (time.hour < 19) {
              distance_to_waking_time = (19 - time.hour - 1) * 3600 + (60 - time.minute) * 60;
          } else if (time.hour >= 23) {
              distance_to_waking_time = maximum_sleep_duration;
          }

          ESP_LOGD("main_loop", "Distance to waking time: %d", distance_to_waking_time);

          auto sleepable_time = distance_to_waking_time < maximum_sleep_duration ? distance_to_waking_time : maximum_sleep_duration;
          if (sleepable_time <= 0) {
              return;
          }

          ESP_LOGD("main_loop", "Outside waking time, sleeping for %d s", sleepable_time);

          ESP.deepSleep(uint64_t(sleepable_time) * 1000000);

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: high
  domain: !secret wifi_domain
  fast_connect: true

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

time:
  - platform: homeassistant
    id: homeassistant_time

mqtt:
  broker: !secret mqtt_broker
  topic_prefix: towelheater

i2c:
  sda: D2
  scl: D1
  scan: True

sensor:
  - platform: uptime
    name: "Towel Heater Uptime"
    id: towel_heater_uptime

  - platform: wifi_signal
    name: "Towel Heater RSSI"
    update_interval: 60s

  - platform: bme280
    temperature:
      name: "BME280 Bathroom Temperature"
      id: bme280_bathroom_temperature
    pressure:
      name: "BME280 Bathroom Pressure"
      id: bme280_bathroom_pressure
    humidity:
      name: "BME280 Bathroom Relative Humidity"
      id: bme280_bathroom_humidity
    address: 0x76
    update_interval: 15s

  - platform: template
    name: "BME280 Bathroom Absolute Humidity"
    lambda: |-
      const float mw = 18.01534;    // molar mass of water g/mol
      const float r = 8.31447215;   // Universal gas constant J/mol/K
      return (6.112 * powf(2.718281828, (17.67 * id(bme280_bathroom_temperature).state) /
        (id(bme280_bathroom_temperature).state + 243.5)) * id(bme280_bathroom_humidity).state * mw) /
        ((273.15 + id(bme280_bathroom_temperature).state) * r); // in grams/m^3
    accuracy_decimals: 2

globals:
  - id: towel_heater_status
    type: bool
    initial_value: 'false'

switch:
  - platform: gpio
    pin: D6
    id: towel_heater_internal_switch

  - platform: template
    name: "Towel Heater"
    icon: mdi:car-defrost-rear
    lambda: 'return id(towel_heater_status);'
    turn_on_action:
      - if:
          condition:
            lambda: 'return id(towel_heater_status) == false;'
          then:
            - lambda: 'id(towel_heater_status) = true;'
            - switch.turn_on: towel_heater_internal_switch
            - delay: 10ms
            - switch.turn_off: towel_heater_internal_switch
    turn_off_action:
      - if:
          condition:
            lambda: 'return id(towel_heater_status) == true;'
          then:
            - lambda: 'id(towel_heater_status) = false;'
            - switch.turn_on: towel_heater_internal_switch
            - delay: 10ms
            - switch.turn_off: towel_heater_internal_switch

  - platform: template
    name: "Deep Sleep"
    turn_on_action:
      - lambda: |-
          ESP.deepSleep(uint64_t(3600) * 1000000);
